# Generated by Django 3.2.6 on 2021-09-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='food_images')),
                ('preparation_time', models.PositiveIntegerField()),
                ('ingredients', models.TextField()),
                ('preparation', models.TextField()),
                ('category', models.CharField(max_length=20)),
                ('native_food_of', models.CharField(blank=True, max_length=20)),
                ('cuisine_type', models.CharField(choices=[('veg', 'Veg'), ('vegan', 'Vegan'), ('eggetarian', 'Eggetarian'), ('non veg', 'Non Veg')], max_length=20)),
            ],
        ),
    ]
