# Generated by Django 3.2.6 on 2021-09-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='cuisine_type',
            field=models.CharField(choices=[('veg', 'Veg'), ('vegan', 'Vegan'), ('eggetarian', 'Eggetarian'), ('non veg', 'Non Veg')], max_length=20),
        ),
    ]
